version: '3'
name: admin-panel

services:
  database:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    image: postgres:16
    volumes:
      - ./db_data:/db_data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 5s
       timeout: 10s
       retries: 5

  admin_panel:
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    build:
      dockerfile: build/movies_admin.Dockerfile
      context: .
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      database:
        condition: service_healthy
